title: Fall Workshop 26
description: Website for Fall Workshop 26
theme: just-the-docs

url: https://cndhsi.github.io/fall-workshop-26

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
